"""Shared GUI components and utilities.

This module provides common widgets, dialogs, and utilities used across
multiple GUI components.
"""

# Dialog styles and constants
# Base dialog class
from modules.gui.shared.base_dialog import BaseDialog

# Context widgets
from modules.gui.shared.context_widgets import (
    ContextChipBase,
    ContextHeaderWidget,
    ContextSectionWidget,
    FlowLayout,
    IconButton,
    ImageContextChip,
    LastInteractionChip,
    LastInteractionHeaderWidget,
    LastInteractionSectionWidget,
    SettingsHeaderWidget,
    SettingsSectionWidget,
    SettingsSelectorChip,
    TextContextChip,
)
from modules.gui.shared.theme import (
    BUTTON_ROW_SPACING,
    CHIP_DISABLED_STYLE,
    CHIP_HOVER_STYLE,
    CHIP_LABEL_DISABLED_STYLE,
    CHIP_LABEL_STYLE,
    CHIP_STYLE,
    COLOR_BORDER,
    COLOR_BUTTON_BG,
    COLOR_BUTTON_DISABLED_BG,
    COLOR_BUTTON_DISABLED_TEXT,
    COLOR_BUTTON_HOVER,
    COLOR_BUTTON_PRESSED,
    COLOR_COMBOBOX_ARROW,
    COLOR_DIALOG_BG,
    COLOR_ERROR_BG,
    COLOR_ERROR_BG_HOVER,
    COLOR_ERROR_BORDER,
    COLOR_NOTIFICATION_BODY,
    COLOR_NOTIFICATION_TITLE,
    COLOR_SCROLLBAR_HANDLE,
    COLOR_SCROLLBAR_HANDLE_HOVER,
    COLOR_SELECTION,
    COLOR_TEXT,
    COLOR_TEXT_EDIT_BG,
    COLOR_TEXT_HINT,
    COLOR_TEXT_LIGHT,
    COLOR_TEXT_LIGHT_GRAY,
    COLOR_TEXT_SECONDARY,
    COLOR_TEXT_WHITE,
    COLOR_TOOLTIP_BG,
    COLOR_TOOLTIP_BORDER,
    COMBOBOX_STYLE,
    DEFAULT_DIALOG_SIZE,
    DEFAULT_WRAPPED_HEIGHT,
    DIALOG_CONTENT_MARGINS,
    DIALOG_SHOW_DELAY_MS,
    DIALOG_STYLESHEET,
    ICON_BTN_STYLE,
    MENU_STYLESHEET,
    MIN_DIALOG_SIZE,
    NOTIFICATION_BODY_STYLE,
    NOTIFICATION_TITLE_STYLE,
    QWIDGETSIZE_MAX,
    SCROLL_CONTENT_MARGINS,
    SCROLL_CONTENT_SPACING,
    SECTION_HINT_STYLE,
    SECTION_TITLE_STYLE,
    SMALL_DIALOG_SIZE,
    SMALL_MIN_DIALOG_SIZE,
    SPINBOX_STYLE,
    SVG_CHEVRON_DOWN_PATH,
    SVG_CHEVRON_UP_PATH,
    TAB_CLOSE_BTN_STYLE,
    TAB_LABEL_STYLE,
    TAB_STYLE,
    TEXT_CHANGE_DEBOUNCE_MS,
    TOOLTIP_STYLE,
    apply_section_size_policy,
    apply_wrap_state,
    create_singleton_dialog_manager,
    get_dialog_stylesheet,
    get_text_edit_content_height,
)

# Image handler
from modules.gui.shared.image_handler import SectionImageHandler

# Undo/redo utilities
from modules.gui.shared.undo_redo import (
    TextEditUndoHelper,
    perform_redo,
    perform_undo,
    save_state_if_changed,
    set_text_with_signal_block,
)

# Shared widgets
from modules.gui.shared.widgets import (
    TEXT_EDIT_MIN_HEIGHT,
    CollapsibleSectionHeader,
    ExpandableTextSection,
    ImageChipContainer,
    ImageChipWidget,
    UndoRedoManager,
    create_text_edit,
)

__all__ = [
    # Theme - timing constants
    "DIALOG_SHOW_DELAY_MS",
    "TEXT_CHANGE_DEBOUNCE_MS",
    "DEFAULT_WRAPPED_HEIGHT",
    "QWIDGETSIZE_MAX",
    # Theme - layout constants
    "DIALOG_CONTENT_MARGINS",
    "SCROLL_CONTENT_MARGINS",
    "SCROLL_CONTENT_SPACING",
    "BUTTON_ROW_SPACING",
    "DEFAULT_DIALOG_SIZE",
    "MIN_DIALOG_SIZE",
    "SMALL_DIALOG_SIZE",
    "SMALL_MIN_DIALOG_SIZE",
    # Theme - colors
    "COLOR_DIALOG_BG",
    "COLOR_TEXT_EDIT_BG",
    "COLOR_TEXT",
    "COLOR_TEXT_WHITE",
    "COLOR_TEXT_SECONDARY",
    "COLOR_TEXT_HINT",
    "COLOR_TEXT_LIGHT_GRAY",
    "COLOR_TEXT_LIGHT",
    "COLOR_NOTIFICATION_TITLE",
    "COLOR_NOTIFICATION_BODY",
    "COLOR_BORDER",
    "COLOR_BUTTON_BG",
    "COLOR_BUTTON_HOVER",
    "COLOR_BUTTON_PRESSED",
    "COLOR_BUTTON_DISABLED_BG",
    "COLOR_BUTTON_DISABLED_TEXT",
    "COLOR_SELECTION",
    "COLOR_SCROLLBAR_HANDLE",
    "COLOR_SCROLLBAR_HANDLE_HOVER",
    "COLOR_TOOLTIP_BG",
    "COLOR_TOOLTIP_BORDER",
    "COLOR_COMBOBOX_ARROW",
    "COLOR_ERROR_BG",
    "COLOR_ERROR_BG_HOVER",
    "COLOR_ERROR_BORDER",
    # Theme - stylesheets
    "TOOLTIP_STYLE",
    "COMBOBOX_STYLE",
    "SPINBOX_STYLE",
    "DIALOG_STYLESHEET",
    "MENU_STYLESHEET",
    "CHIP_STYLE",
    "CHIP_HOVER_STYLE",
    "CHIP_DISABLED_STYLE",
    "CHIP_LABEL_STYLE",
    "CHIP_LABEL_DISABLED_STYLE",
    "SECTION_TITLE_STYLE",
    "SECTION_HINT_STYLE",
    "ICON_BTN_STYLE",
    "TAB_STYLE",
    "TAB_LABEL_STYLE",
    "TAB_CLOSE_BTN_STYLE",
    "NOTIFICATION_TITLE_STYLE",
    "NOTIFICATION_BODY_STYLE",
    # Theme - paths
    "SVG_CHEVRON_DOWN_PATH",
    "SVG_CHEVRON_UP_PATH",
    # Theme - functions
    "get_dialog_stylesheet",
    "get_text_edit_content_height",
    "apply_wrap_state",
    "apply_section_size_policy",
    "create_singleton_dialog_manager",
    # Base dialog
    "BaseDialog",
    # Context widgets
    "IconButton",
    "ContextChipBase",
    "TextContextChip",
    "ImageContextChip",
    "ContextHeaderWidget",
    "FlowLayout",
    "ContextSectionWidget",
    "LastInteractionChip",
    "LastInteractionHeaderWidget",
    "LastInteractionSectionWidget",
    "SettingsSelectorChip",
    "SettingsHeaderWidget",
    "SettingsSectionWidget",
    # Shared widgets
    "TEXT_EDIT_MIN_HEIGHT",
    "CollapsibleSectionHeader",
    "ImageChipWidget",
    "create_text_edit",
    "ExpandableTextSection",
    "UndoRedoManager",
    "ImageChipContainer",
    # Undo/redo
    "perform_undo",
    "perform_redo",
    "save_state_if_changed",
    "set_text_with_signal_block",
    "TextEditUndoHelper",
    # Image handler
    "SectionImageHandler",
]
